create table openpowerlifting.lifter_iceberg (
    name string,
    sex string,
    event string,
    equipment string,
    age string,
    ageclass string,
    birthyearclass string,
    division string,
    bodyweightkg string,
    weightclasskg string,
    squat1kg string,
    squat2kg string,
    squat3kg string,
    squat4kg string,
    best3squatkg string,
    bench1kg string,
    bench2kg string,
    bench3kg string,
    bench4kg string,
    best3benchkg string,
    deadlift1kg string,
    deadlift2kg string,
    deadlift3kg string,
    deadlift4kg string,
    best3deadliftkg string,
    totalkg string,
    place string,
    dots string,
    wilks string,
    glossbrenner string,
    goodlift string,
    tested string,
    country string,
    state string,
    federation string,
    parentfederation string,
    date string,
    meetcountry string,
    meetstate string,
    meettown string,
    meetname string,
    sanctioned string,
    downloaded_at timestamp,
    created_date string
)
partitioned by (created_date)
location 's3://tdouglas-data-prod-useast2/data/raw/openpowerlifting/lifter_iceberg/'
tblproperties (
    'table_type' = 'ICEBERG',
    'format'='parquet',
    'write_compression'='snappy',
    'optimize_rewrite_delete_file_threshold'='10'
)
